<?php

/**
 * @file
 * Basic Display settings for ERCore module entity types.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function ercore_ds_ctools_plugin_api($module, $api) {
  if ($module == 'ds' && $api == 'ds') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_install().
 */
function ercore_ds_install() {
  variable_set('ds_extras_field_template', '1');
  variable_set('ds_classes_fields', 'h2|Heading 2
h3|Heading 3
h4|Heading 4
pull-right|Pull Right
pull-left|Pull Left
date|Dates
teaser-date|Teaser Dates
featured-field|Featured Field'
    );
}

/**
 * Implements hook_uninstall().
 */
function ercore_ds_uninstall() {

}