<?php
/**
 * @file
 * Includes array of ERCore Engagement field definitions.
 */

$ercore_engagement_definitions = array(
// FIELD: field_ercore_ee_ari_fac_f.
  'ee_field_ercore_ee_ari_fac_f' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_ari_fac_f' => array(
              'value' => 'field_ercore_ee_ari_fac_f_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_ari_fac_f' => array(
              'value' => 'field_ercore_ee_ari_fac_f_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_ari_fac_f',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_ari_fac_m.
  'ee_field_ercore_ee_ari_fac_m' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_ari_fac_m' => array(
              'value' => 'field_ercore_ee_ari_fac_m_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_ari_fac_m' => array(
              'value' => 'field_ercore_ee_ari_fac_m_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_ari_fac_m',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_ari_fac_u.
  'ee_field_ercore_ee_ari_fac_u' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_ari_fac_u' => array(
              'value' => 'field_ercore_ee_ari_fac_u_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_ari_fac_u' => array(
              'value' => 'field_ercore_ee_ari_fac_u_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_ari_fac_u',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_ari_stu_f.
  'ee_field_ercore_ee_ari_stu_f' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_ari_stu_f' => array(
              'value' => 'field_ercore_ee_ari_stu_f_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_ari_stu_f' => array(
              'value' => 'field_ercore_ee_ari_stu_f_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_ari_stu_f',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_ari_stu_m.
  'ee_field_ercore_ee_ari_stu_m' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_ari_stu_m' => array(
              'value' => 'field_ercore_ee_ari_stu_m_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_ari_stu_m' => array(
              'value' => 'field_ercore_ee_ari_stu_m_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_ari_stu_m',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_ari_stu_u.
  'ee_field_ercore_ee_ari_stu_u' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_ari_stu_u' => array(
              'value' => 'field_ercore_ee_ari_stu_u_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_ari_stu_u' => array(
              'value' => 'field_ercore_ee_ari_stu_u_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_ari_stu_u',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_ee_file.
  'ee_field_ercore_ee_ee_file' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'display_field' => 0,
      'display_default' => 0,
      'uri_scheme' => 'public',
      'profile2_private' => FALSE,
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_ee_file' => array(
              'fid' => 'field_ercore_ee_ee_file_fid',
              'display' => 'field_ercore_ee_ee_file_display',
              'description' => 'field_ercore_ee_ee_file_description',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_ee_file' => array(
              'fid' => 'field_ercore_ee_ee_file_fid',
              'display' => 'field_ercore_ee_ee_file_display',
              'description' => 'field_ercore_ee_ee_file_description',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(
      'fid' => array(
        'table' => 'file_managed',
        'columns' => array(
          'fid' => 'fid',
        ),
      ),
    ),
    'indexes' => array(
      'fid' => array(
        'fid',
      ),
    ),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_ee_file',
    'type' => 'file',
    'module' => 'file',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'fid' => array(
        'description' => 'The {file_managed}.fid being referenced in this field.',
        'type' => 'int',
        'not null' => FALSE,
        'unsigned' => TRUE,
      ),
      'display' => array(
        'description' => 'Flag to control whether this file should be displayed when viewing content.',
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 1,
      ),
      'description' => array(
        'description' => 'A description of the file.',
        'type' => 'text',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_estimated.
  'ee_field_ercore_ee_estimated' => array(
    'entity_types' => array(),
    'settings' => array(
      'allowed_values' => array(
        'These values have not been estimated and are precise',
        'These values have been estimated',
      ),
      'allowed_values_function' => '',
      'prefix' => '',
      'suffix' => '',
      'min' => '',
      'max' => '',
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_estimated' => array(
              'value' => 'field_ercore_ee_estimated_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_estimated' => array(
              'value' => 'field_ercore_ee_estimated_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(
      'value' => array(
        'value',
      ),
    ),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_estimated',
    'type' => 'list_boolean',
    'module' => 'list',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_stud_f.
  'ee_field_ercore_ee_k12i_stud_f' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_stud_f' => array(
              'value' => 'field_ercore_ee_k12i_stud_f_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_stud_f' => array(
              'value' => 'field_ercore_ee_k12i_stud_f_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_stud_f',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_stud_m.
  'ee_field_ercore_ee_k12i_stud_m' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_stud_m' => array(
              'value' => 'field_ercore_ee_k12i_stud_m_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_stud_m' => array(
              'value' => 'field_ercore_ee_k12i_stud_m_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_stud_m',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_stud_u.
  'ee_field_ercore_ee_k12i_stud_u' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_stud_u' => array(
              'value' => 'field_ercore_ee_k12i_stud_u_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_stud_u' => array(
              'value' => 'field_ercore_ee_k12i_stud_u_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_stud_u',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_stut_f.
  'ee_field_ercore_ee_k12i_stut_f' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_stut_f' => array(
              'value' => 'field_ercore_ee_k12i_stut_f_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_stut_f' => array(
              'value' => 'field_ercore_ee_k12i_stut_f_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_stut_f',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_stut_m.
  'ee_field_ercore_ee_k12i_stut_m' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_stut_m' => array(
              'value' => 'field_ercore_ee_k12i_stut_m_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_stut_m' => array(
              'value' => 'field_ercore_ee_k12i_stut_m_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_stut_m',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_stut_u.
  'ee_field_ercore_ee_k12i_stut_u' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_stut_u' => array(
              'value' => 'field_ercore_ee_k12i_stut_u_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_stut_u' => array(
              'value' => 'field_ercore_ee_k12i_stut_u_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_stut_u',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_tec_f.
  'ee_field_ercore_ee_k12i_tec_f' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_tec_f' => array(
              'value' => 'field_ercore_ee_k12i_tec_f_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_tec_f' => array(
              'value' => 'field_ercore_ee_k12i_tec_f_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_tec_f',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_tec_m.
  'ee_field_ercore_ee_k12i_tec_m' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_tec_m' => array(
              'value' => 'field_ercore_ee_k12i_tec_m_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_tec_m' => array(
              'value' => 'field_ercore_ee_k12i_tec_m_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_tec_m',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_tec_u.
  'ee_field_ercore_ee_k12i_tec_u' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_tec_u' => array(
              'value' => 'field_ercore_ee_k12i_tec_u_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_tec_u' => array(
              'value' => 'field_ercore_ee_k12i_tec_u_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_tec_u',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_msi_fac_f.
  'ee_field_ercore_ee_msi_fac_f' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_msi_fac_f' => array(
              'value' => 'field_ercore_ee_msi_fac_f_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_msi_fac_f' => array(
              'value' => 'field_ercore_ee_msi_fac_f_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_msi_fac_f',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_msi_fac_m.
  'ee_field_ercore_ee_msi_fac_m' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_msi_fac_m' => array(
              'value' => 'field_ercore_ee_msi_fac_m_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_msi_fac_m' => array(
              'value' => 'field_ercore_ee_msi_fac_m_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_msi_fac_m',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_msi_fac_u.
  'ee_field_ercore_ee_msi_fac_u' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_msi_fac_u' => array(
              'value' => 'field_ercore_ee_msi_fac_u_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_msi_fac_u' => array(
              'value' => 'field_ercore_ee_msi_fac_u_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_msi_fac_u',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_msi_stu_f.
  'ee_field_ercore_ee_msi_stu_f' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_msi_stu_f' => array(
              'value' => 'field_ercore_ee_msi_stu_f_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_msi_stu_f' => array(
              'value' => 'field_ercore_ee_msi_stu_f_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_msi_stu_f',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_msi_stu_m.
  'ee_field_ercore_ee_msi_stu_m' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_msi_stu_m' => array(
              'value' => 'field_ercore_ee_msi_stu_m_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_msi_stu_m' => array(
              'value' => 'field_ercore_ee_msi_stu_m_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_msi_stu_m',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_msi_stu_u.
  'ee_field_ercore_ee_msi_stu_u' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_msi_stu_u' => array(
              'value' => 'field_ercore_ee_msi_stu_u_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_msi_stu_u' => array(
              'value' => 'field_ercore_ee_msi_stu_u_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_msi_stu_u',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_oth_f.
  'ee_field_ercore_ee_oth_f' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_oth_f' => array(
              'value' => 'field_ercore_ee_oth_f_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_oth_f' => array(
              'value' => 'field_ercore_ee_oth_f_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_oth_f',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_oth_m.
  'ee_field_ercore_ee_oth_m' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_oth_m' => array(
              'value' => 'field_ercore_ee_oth_m_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_oth_m' => array(
              'value' => 'field_ercore_ee_oth_m_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_oth_m',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_oth_u.
  'ee_field_ercore_ee_oth_u' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_oth_u' => array(
              'value' => 'field_ercore_ee_oth_u_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_oth_u' => array(
              'value' => 'field_ercore_ee_oth_u_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_oth_u',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_pui_fac_f.
  'ee_field_ercore_ee_pui_fac_f' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_pui_fac_f' => array(
              'value' => 'field_ercore_ee_pui_fac_f_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_pui_fac_f' => array(
              'value' => 'field_ercore_ee_pui_fac_f_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_pui_fac_f',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_pui_fac_m.
  'ee_field_ercore_ee_pui_fac_m' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_pui_fac_m' => array(
              'value' => 'field_ercore_ee_pui_fac_m_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_pui_fac_m' => array(
              'value' => 'field_ercore_ee_pui_fac_m_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_pui_fac_m',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_pui_fac_u.
  'ee_field_ercore_ee_pui_fac_u' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_pui_fac_u' => array(
              'value' => 'field_ercore_ee_pui_fac_u_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_pui_fac_u' => array(
              'value' => 'field_ercore_ee_pui_fac_u_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_pui_fac_u',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_pui_stu_f.
  'ee_field_ercore_ee_pui_stu_f' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_pui_stu_f' => array(
              'value' => 'field_ercore_ee_pui_stu_f_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_pui_stu_f' => array(
              'value' => 'field_ercore_ee_pui_stu_f_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_pui_stu_f',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_pui_stu_m.
  'ee_field_ercore_ee_pui_stu_m' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_pui_stu_m' => array(
              'value' => 'field_ercore_ee_pui_stu_m_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_pui_stu_m' => array(
              'value' => 'field_ercore_ee_pui_stu_m_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_pui_stu_m',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_pui_stu_u.
  'ee_field_ercore_ee_pui_stu_u' => array(
    'entity_types' => array(),
    'settings' => array(
      'prefix' => '',
      'suffix' => '',
      'min' => '0',
      'max' => '',
      'allowed_values' => array(),
      'allowed_values_php' => '',
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_pui_stu_u' => array(
              'value' => 'field_ercore_ee_pui_stu_u_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_pui_stu_u' => array(
              'value' => 'field_ercore_ee_pui_stu_u_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_pui_stu_u',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_ari_stu_mn.
  'ee_field_ercore_ee_ari_stu_mn' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_ari_stu_mn' => array(
              'value' => 'field_ercore_ee_ari_stu_mn_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_ari_stu_mn' => array(
              'value' => 'field_ercore_ee_ari_stu_mn_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_ari_stu_mn',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_tec_mn.
  'ee_field_ercore_ee_k12i_tec_mn' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_tec_mn' => array(
              'value' => 'field_ercore_ee_k12i_tec_mn_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_tec_mn' => array(
              'value' => 'field_ercore_ee_k12i_tec_mn_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_tec_mn',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_stud_mn.
  'ee_field_ercore_ee_k12i_stud_mn' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_stud_mn' => array(
              'value' => 'field_ercore_ee_k12i_stud_mn_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_stud_mn' => array(
              'value' => 'field_ercore_ee_k12i_stud_mn_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_stud_mn',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_stut_mn.
  'ee_field_ercore_ee_k12i_stut_mn' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_stut_mn' => array(
              'value' => 'field_ercore_ee_k12i_stut_mn_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_stut_mn' => array(
              'value' => 'field_ercore_ee_k12i_stut_mn_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_stut_mn',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_oth_mn.
  'ee_field_ercore_ee_oth_mn' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_oth_mn' => array(
              'value' => 'field_ercore_ee_oth_mn_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_oth_mn' => array(
              'value' => 'field_ercore_ee_oth_mn_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_oth_mn',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_pui_fac_mn.
  'ee_field_ercore_ee_pui_fac_mn' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_pui_fac_mn' => array(
              'value' => 'field_ercore_ee_pui_fac_mn_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_pui_fac_mn' => array(
              'value' => 'field_ercore_ee_pui_fac_mn_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_pui_fac_mn',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_pui_stu_mn.
  'ee_field_ercore_ee_pui_stu_mn' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_pui_stu_mn' => array(
              'value' => 'field_ercore_ee_pui_stu_mn_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_pui_stu_mn' => array(
              'value' => 'field_ercore_ee_pui_stu_mn_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_pui_stu_mn',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_ari_fac_mn.
  'ee_field_ercore_ee_ari_fac_mn' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_ari_fac_mn' => array(
              'value' => 'field_ercore_ee_ari_fac_mn_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_ari_fac_mn' => array(
              'value' => 'field_ercore_ee_ari_fac_mn_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_ari_fac_mn',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_msi_fac_mn.
  'ee_field_ercore_ee_msi_fac_mn' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_msi_fac_mn' => array(
              'value' => 'field_ercore_ee_msi_fac_mn_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_msi_fac_mn' => array(
              'value' => 'field_ercore_ee_msi_fac_mn_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_msi_fac_mn',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_msi_stu_mn.
  'ee_field_ercore_ee_msi_stu_mn' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_msi_stu_mn' => array(
              'value' => 'field_ercore_ee_msi_stu_mn_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_msi_stu_mn' => array(
              'value' => 'field_ercore_ee_msi_stu_mn_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_msi_stu_mn',
    'type' => 'number_integer',
    'module' => 'number',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_oth_t.
  'ee_field_ercore_ee_oth_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' =>
      '$value_f = $entity->field_ercore_ee_oth_f[\'und\'][0][\'value\'];
        $value_m = $entity->field_ercore_ee_oth_m[\'und\'][0][\'value\'];
        $value_u = $entity->field_ercore_ee_oth_u[\'und\'][0][\'value\'];
        $entity_field[0][\'value\'] = $value_f + $value_m + $value_u;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_oth_t' => array(
              'value' => 'field_ercore_ee_oth_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_oth_t' => array(
              'value' => 'field_ercore_ee_oth_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_oth_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_stut_t.
  'ee_field_ercore_ee_k12i_stut_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' =>
      '$value_f = $entity->field_ercore_ee_k12i_stut_f[\'und\'][0][\'value\'];
        $value_m = $entity->field_ercore_ee_k12i_stut_m[\'und\'][0][\'value\'];
        $value_u = $entity->field_ercore_ee_k12i_stut_u[\'und\'][0][\'value\'];
        $entity_field[0][\'value\'] = $value_f + $value_m + $value_u;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_stut_t' => array(
              'value' => 'field_ercore_ee_k12i_stut_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_stut_t' => array(
              'value' => 'field_ercore_ee_k12i_stut_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_stut_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_stud_t.
  'ee_field_ercore_ee_k12i_stud_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' =>
      '$value_f = $entity->field_ercore_ee_k12i_stud_f[\'und\'][0][\'value\'];
        $value_m = $entity->field_ercore_ee_k12i_stud_m[\'und\'][0][\'value\'];
        $value_u = $entity->field_ercore_ee_k12i_stud_u[\'und\'][0][\'value\'];
        $entity_field[0][\'value\'] = $value_f + $value_m + $value_u;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_stud_t' => array(
              'value' => 'field_ercore_ee_k12i_stud_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_stud_t' => array(
              'value' => 'field_ercore_ee_k12i_stud_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_stud_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_k12i_tec_t.
  'ee_field_ercore_ee_k12i_tec_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' =>
      '$value_f = $entity->field_ercore_ee_k12i_tec_f[\'und\'][0][\'value\'];
        $value_m = $entity->field_ercore_ee_k12i_tec_m[\'und\'][0][\'value\'];
        $value_u = $entity->field_ercore_ee_k12i_tec_u[\'und\'][0][\'value\'];
        $entity_field[0][\'value\'] = $value_f + $value_m + $value_u;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_k12i_tec_t' => array(
              'value' => 'field_ercore_ee_k12i_tec_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_k12i_tec_t' => array(
              'value' => 'field_ercore_ee_k12i_tec_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_k12i_tec_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_msi_fac_t.
  'ee_field_ercore_ee_msi_fac_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' =>
      '$value_f = $entity->field_ercore_ee_msi_fac_f[\'und\'][0][\'value\'];
        $value_m = $entity->field_ercore_ee_msi_fac_m[\'und\'][0][\'value\'];
        $value_u = $entity->field_ercore_ee_msi_fac_u[\'und\'][0][\'value\'];
        $entity_field[0][\'value\'] = $value_f + $value_m + $value_u;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_msi_fac_t' => array(
              'value' => 'field_ercore_ee_msi_fac_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_msi_fac_t' => array(
              'value' => 'field_ercore_ee_msi_fac_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_msi_fac_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_msi_stu_t.
  'ee_field_ercore_ee_msi_stu_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' =>
      '$value_f = $entity->field_ercore_ee_msi_stu_f[\'und\'][0][\'value\'];
        $value_m = $entity->field_ercore_ee_msi_stu_m[\'und\'][0][\'value\'];
        $value_u = $entity->field_ercore_ee_msi_stu_u[\'und\'][0][\'value\'];
        $entity_field[0][\'value\'] = $value_f + $value_m + $value_u;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_msi_stu_t' => array(
              'value' => 'field_ercore_ee_msi_stu_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_msi_stu_t' => array(
              'value' => 'field_ercore_ee_msi_stu_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_msi_stu_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_pui_stu_t.
  'ee_field_ercore_ee_pui_stu_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' =>
      '$value_f = $entity->field_ercore_ee_pui_stu_f[\'und\'][0][\'value\'];
        $value_m = $entity->field_ercore_ee_pui_stu_m[\'und\'][0][\'value\'];
        $value_u = $entity->field_ercore_ee_pui_stu_u[\'und\'][0][\'value\'];
        $entity_field[0][\'value\'] = $value_f + $value_m + $value_u;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_pui_stu_t' => array(
              'value' => 'field_ercore_ee_pui_stu_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_pui_stu_t' => array(
              'value' => 'field_ercore_ee_pui_stu_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_pui_stu_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_pui_fac_t.
  'ee_field_ercore_ee_pui_fac_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' =>
      '$value_f = $entity->field_ercore_ee_pui_fac_f[\'und\'][0][\'value\'];
        $value_m = $entity->field_ercore_ee_pui_fac_m[\'und\'][0][\'value\'];
        $value_u = $entity->field_ercore_ee_pui_fac_u[\'und\'][0][\'value\'];
        $entity_field[0][\'value\'] = $value_f + $value_m + $value_u;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_pui_fac_t' => array(
              'value' => 'field_ercore_ee_pui_fac_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_pui_fac_t' => array(
              'value' => 'field_ercore_ee_pui_fac_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_pui_fac_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_ari_stu_t.
  'ee_field_ercore_ee_ari_stu_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' =>
      '$value_f = $entity->field_ercore_ee_ari_stu_f[\'und\'][0][\'value\'];
        $value_m = $entity->field_ercore_ee_ari_stu_m[\'und\'][0][\'value\'];
        $value_u = $entity->field_ercore_ee_ari_stu_u[\'und\'][0][\'value\'];

    $entity_field[0][\'value\'] = $value_f + $value_m + $value_u;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_ari_stu_t' => array(
              'value' => 'field_ercore_ee_ari_stu_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_ari_stu_t' => array(
              'value' => 'field_ercore_ee_ari_stu_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_ari_stu_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_ari_fac_t.
  'ee_field_ercore_ee_ari_fac_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' =>
      '$value_f = $entity->field_ercore_ee_ari_fac_f[\'und\'][0][\'value\'];
        $value_m = $entity->field_ercore_ee_ari_fac_m[\'und\'][0][\'value\'];
        $value_u = $entity->field_ercore_ee_ari_fac_u[\'und\'][0][\'value\'];

    $entity_field[0][\'value\'] = $value_f + $value_m + $value_u;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_ari_fac_t' => array(
              'value' => 'field_ercore_ee_ari_fac_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_ari_fac_t' => array(
              'value' => 'field_ercore_ee_ari_fac_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_ari_fac_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_t_t.
  'ee_field_ercore_ee_t_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' => '// ARI Fields
    $value_ari_stu_f = $entity->field_ercore_ee_ari_stu_f[\'und\'][0][\'value\'];
    $value_ari_stu_m = $entity->field_ercore_ee_ari_stu_m[\'und\'][0][\'value\'];
    $value_ari_stu_u = $entity->field_ercore_ee_ari_stu_u[\'und\'][0][\'value\'];
    $value_ari_fac_f = $entity->field_ercore_ee_ari_fac_f[\'und\'][0][\'value\'];
    $value_ari_fac_m = $entity->field_ercore_ee_ari_fac_m[\'und\'][0][\'value\'];
    $value_ari_fac_u = $entity->field_ercore_ee_ari_fac_u[\'und\'][0][\'value\'];
    // PUI Fields
    $value_pui_stu_f = $entity->field_ercore_ee_pui_stu_f[\'und\'][0][\'value\'];
    $value_pui_stu_m = $entity->field_ercore_ee_pui_stu_m[\'und\'][0][\'value\'];
    $value_pui_stu_u = $entity->field_ercore_ee_pui_stu_u[\'und\'][0][\'value\'];
    $value_pui_fac_f = $entity->field_ercore_ee_pui_fac_f[\'und\'][0][\'value\'];
    $value_pui_fac_m = $entity->field_ercore_ee_pui_fac_m[\'und\'][0][\'value\'];
    $value_pui_fac_u = $entity->field_ercore_ee_pui_fac_u[\'und\'][0][\'value\'];
    // MSI Fields
    $value_msi_stu_f = $entity->field_ercore_ee_msi_stu_f[\'und\'][0][\'value\'];
    $value_msi_stu_m = $entity->field_ercore_ee_msi_stu_m[\'und\'][0][\'value\'];
    $value_msi_stu_u = $entity->field_ercore_ee_msi_stu_u[\'und\'][0][\'value\'];
    $value_msi_fac_f = $entity->field_ercore_ee_msi_fac_f[\'und\'][0][\'value\'];
    $value_msi_fac_m = $entity->field_ercore_ee_msi_fac_m[\'und\'][0][\'value\'];
    $value_msi_fac_u = $entity->field_ercore_ee_msi_fac_u[\'und\'][0][\'value\'];
    // K12 fields
    $value_k12t_f = $entity->field_ercore_ee_k12i_tec_f[\'und\'][0][\'value\'];
    $value_k12t_m = $entity->field_ercore_ee_k12i_tec_m[\'und\'][0][\'value\'];
    $value_k12t_u = $entity->field_ercore_ee_k12i_tec_u[\'und\'][0][\'value\'];
    $value_k12d_f = $entity->field_ercore_ee_k12i_stud_f[\'und\'][0][\'value\'];
    $value_k12d_m = $entity->field_ercore_ee_k12i_stud_m[\'und\'][0][\'value\'];
    $value_k12d_u = $entity->field_ercore_ee_k12i_stud_u[\'und\'][0][\'value\'];
    $value_k12tt_f = $entity->field_ercore_ee_k12i_stut_f[\'und\'][0][\'value\'];
    $value_k12tt_m = $entity->field_ercore_ee_k12i_stut_m[\'und\'][0][\'value\'];
    $value_k12tt_u = $entity->field_ercore_ee_k12i_stut_u[\'und\'][0][\'value\'];
    // Other fields
    $value_oth_f = $entity->field_ercore_ee_oth_f[\'und\'][0][\'value\'];
    $value_oth_m = $entity->field_ercore_ee_oth_m[\'und\'][0][\'value\'];
    $value_oth_u = $entity->field_ercore_ee_oth_u[\'und\'][0][\'value\'];

    // Total
    $entity_field[0][\'value\'] = $value_ari_stu_f +
      $value_ari_stu_m +
      $value_ari_stu_u +
      $value_ari_fac_f +
      $value_ari_fac_m +
      $value_ari_fac_u +
      $value_pui_stu_f +
      $value_pui_stu_m +
      $value_pui_stu_u +
      $value_pui_fac_f +
      $value_pui_fac_m +
      $value_pui_fac_u +
      $value_msi_stu_f +
      $value_msi_stu_m +
      $value_msi_stu_u +
      $value_msi_fac_f +
      $value_msi_fac_m +
      $value_msi_fac_u +
      $value_k12t_f +
      $value_k12t_m +
      $value_k12t_u +
      $value_k12d_f +
      $value_k12d_m +
      $value_k12d_u +
      $value_k12tt_f +
      $value_k12tt_m +
      $value_k12tt_u +
      $value_oth_f +
      $value_oth_m +
      $value_oth_u;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_t_t' => array(
              'value' => 'field_ercore_ee_t_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_t_t' => array(
              'value' => 'field_ercore_ee_t_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_t_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_f_t.
  'ee_field_ercore_ee_f_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' => '// ARI Fields
    $value_ari_stu_f = $entity->field_ercore_ee_ari_stu_f[\'und\'][0][\'value\'];
    $value_ari_fac_f = $entity->field_ercore_ee_ari_fac_f[\'und\'][0][\'value\'];
    // PUI Fields
    $value_pui_stu_f = $entity->field_ercore_ee_pui_stu_f[\'und\'][0][\'value\'];
    $value_pui_fac_f = $entity->field_ercore_ee_pui_fac_f[\'und\'][0][\'value\'];
    // MSI Fields
    $value_msi_stu_f = $entity->field_ercore_ee_msi_stu_f[\'und\'][0][\'value\'];
    $value_msi_fac_f = $entity->field_ercore_ee_msi_fac_f[\'und\'][0][\'value\'];
    // K12 fields
    $value_k12t_f = $entity->field_ercore_ee_k12i_tec_f[\'und\'][0][\'value\'];
    $value_k12d_f = $entity->field_ercore_ee_k12i_stud_f[\'und\'][0][\'value\'];
    $value_k12tt_f = $entity->field_ercore_ee_k12i_stut_f[\'und\'][0][\'value\'];
    // Other fields
    $value_oth_f = $entity->field_ercore_ee_oth_f[\'und\'][0][\'value\'];

    // Total
    $entity_field[0][\'value\'] = $value_ari_stu_f +
    $value_ari_fac_f +
    $value_pui_stu_f +
    $value_pui_fac_f +
    $value_msi_stu_f +
    $value_msi_fac_f +
    $value_k12t_f +
    $value_k12d_f +
    $value_k12tt_f +
    $value_oth_f;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_f_t' => array(
              'value' => 'field_ercore_ee_f_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_f_t' => array(
              'value' => 'field_ercore_ee_f_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_f_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_m_t.
  'ee_field_ercore_ee_m_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' => '// ARI Fields
    $value_ari_stu_m = $entity->field_ercore_ee_ari_stu_m[\'und\'][0][\'value\'];
    $value_ari_fac_m = $entity->field_ercore_ee_ari_fac_m[\'und\'][0][\'value\'];
    // PUI Fields
    $value_pui_stu_m = $entity->field_ercore_ee_pui_stu_m[\'und\'][0][\'value\'];
    $value_pui_fac_m = $entity->field_ercore_ee_pui_fac_m[\'und\'][0][\'value\'];
    // MSI Fields
    $value_msi_stu_m = $entity->field_ercore_ee_msi_stu_m[\'und\'][0][\'value\'];
    $value_msi_fac_m = $entity->field_ercore_ee_msi_fac_m[\'und\'][0][\'value\'];
    // K12 fields
    $value_k12t_m = $entity->field_ercore_ee_k12i_tec_m[\'und\'][0][\'value\'];
    $value_k12d_m = $entity->field_ercore_ee_k12i_stud_m[\'und\'][0][\'value\'];
    $value_k12tt_m = $entity->field_ercore_ee_k12i_stut_m[\'und\'][0][\'value\'];
    // Other fields
    $value_oth_m = $entity->field_ercore_ee_oth_m[\'und\'][0][\'value\'];

    // Total
    $entity_field[0][\'value\'] = $value_ari_stu_m +
      $value_ari_fac_m + $value_pui_stu_m + $value_pui_fac_m +
      $value_msi_stu_m +
      $value_msi_fac_m +
      $value_k12t_m +
      $value_k12d_m +
      $value_k12tt_m +
      $value_oth_m;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_m_t' => array(
              'value' => 'field_ercore_ee_m_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_m_t' => array(
              'value' => 'field_ercore_ee_m_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_m_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_u_t.
  'ee_field_ercore_ee_u_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' => '// ARI Fields
    $value_ari_stu_u = $entity->field_ercore_ee_ari_stu_u[\'und\'][0][\'value\'];
    $value_ari_fac_u = $entity->field_ercore_ee_ari_fac_u[\'und\'][0][\'value\'];
    // PUI Fields
    $value_pui_stu_u = $entity->field_ercore_ee_pui_stu_u[\'und\'][0][\'value\'];
    $value_pui_fac_u = $entity->field_ercore_ee_pui_fac_u[\'und\'][0][\'value\'];
    // MSI Fields
    $value_msi_stu_u = $entity->field_ercore_ee_msi_stu_u[\'und\'][0][\'value\'];
    $value_msi_fac_u = $entity->field_ercore_ee_msi_fac_u[\'und\'][0][\'value\'];
    // K12 fields
    $value_k12t_u = $entity->field_ercore_ee_k12i_tec_u[\'und\'][0][\'value\'];
    $value_k12d_u = $entity->field_ercore_ee_k12i_stud_u[\'und\'][0][\'value\'];
    $value_k12tt_u = $entity->field_ercore_ee_k12i_stut_u[\'und\'][0][\'value\'];
    // Other fields
    $value_oth_u = $entity->field_ercore_ee_oth_u[\'und\'][0][\'value\'];

    // Total
    $entity_field[0][\'value\'] = $value_ari_stu_u +
      $value_ari_fac_u +
      $value_pui_stu_u +
      $value_pui_fac_u +
      $value_msi_stu_u +
      $value_msi_fac_u +
      $value_k12t_u +
      $value_k12d_u +
      $value_k12tt_u +
      $value_oth_u;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_u_t' => array(
              'value' => 'field_ercore_ee_u_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_u_t' => array(
              'value' => 'field_ercore_ee_u_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_u_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),
// FIELD: field_ercore_ee_um_t.
  'ee_field_ercore_ee_um_t' => array(
    'translatable' => '0',
    'entity_types' => array(),
    'settings' => array(
      'code' => '// ARI Fields
    $value_ari_stu_mn = $entity->field_ercore_ee_ari_stu_mn[\'und\'][0][\'value\'];
    $value_ari_fac_mn = $entity->field_ercore_ee_ari_fac_mn[\'und\'][0][\'value\'];
    // PUI Fields
    $value_pui_stu_mn = $entity->field_ercore_ee_pui_stu_mn[\'und\'][0][\'value\'];
    $value_pui_fac_mn = $entity->field_ercore_ee_pui_fac_mn[\'und\'][0][\'value\'];
    // MSI Fields
    $value_msi_stu_mn = $entity->field_ercore_ee_msi_stu_mn[\'und\'][0][\'value\'];
    $value_msi_fac_mn = $entity->field_ercore_ee_msi_fac_mn[\'und\'][0][\'value\'];
    // K12 fields
    $value_k12t_mn = $entity->field_ercore_ee_k12i_tec_mn[\'und\'][0][\'value\'];
    $value_k12d_mn = $entity->field_ercore_ee_k12i_stud_mn[\'und\'][0][\'value\'];
    $value_k12tt_mn = $entity->field_ercore_ee_k12i_stut_mn[\'und\'][0][\'value\'];
    // Other fields
    $value_oth_mn = $entity->field_ercore_ee_oth_mn[\'und\'][0][\'value\'];

    // Total
    $entity_field[0][\'value\'] = $value_ari_stu_mn +
      $value_ari_fac_mn +
      $value_pui_stu_mn +
      $value_pui_fac_mn +
      $value_msi_stu_mn +
      $value_msi_fac_mn +
      $value_k12t_mn +
      $value_k12d_mn +
      $value_k12tt_mn +
      $value_oth_mn;',
      'display_format' => '$display_output = $entity_field_item[\'value\'];',
      'store' => 1,
      'database' => array(
        'data_type' => 'int',
        'data_length' => '32',
        'data_size' => 'normal',
        'data_precision' => '10',
        'data_scale' => '2',
        'data_default' => '',
        'data_not_NULL' => 1,
        'data_index' => 0,
      ),
    ),
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_ercore_ee_um_t' => array(
              'value' => 'field_ercore_ee_um_t_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_ercore_ee_um_t' => array(
              'value' => 'field_ercore_ee_um_t_value',
            ),
          ),
        ),
      ),
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'field_permissions' => array(
      'type' => '0',
    ),
    'field_name' => 'field_ercore_ee_um_t',
    'type' => 'computed',
    'module' => 'computed_field',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => 1,
      ),
    ),
    'bundles' => array(
      'field_collection_item' => array(
        'field_ercore_ev_engagement',
      ),
    ),
  ),

);
