<?php

/**
 * @file
 * Module file for the ERCore Admin module.
 */

/**
 * Implements hook_permission().
 */
function ercore_admin_permission() {
  return array(
    'access ercore admin help' => array(
      'title' => t('Access ERCore Admin Help Page'),
      'description' => t('Allow users to access Administrative Help Page.'),
    ),
  );
}

/**
 * Implements hook_help().
 */
/*function ercore_admin_help($path, $arg) {
switch ($path) {
case 'admin/help#ercore_admin':
return t("No ERCore help available at this time.");
}
}*/

/**
 * Implements hook_menu().
 */
function ercore_admin_menu() {
  $items['reporting'] = array(
    'title' => 'Accomplishments',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ercore_reporting_callback'),
    'access arguments' => array('access ercore admin content'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'file' => 'pages/ercore-reporting.inc',
  );
  $items['ercore'] = array(
    'menu_name' => 'ercore_admin_menu',
    'title' => 'ERCore',
    'description' => 'ERCore is a Drupal project to assist in the collection, display, and preparation of EPSCoR grant data.',
    'expanded' => '1',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access ercore content'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  // ERCore Content Menu, accomplishments table views point here.
  $items['ercore/content'] = array(
    // 'menu_name' => 'ercore_admin_menu',.
    'title' => 'ERCore Content',
    'description' => 'All ERCore related content types that come with the
    ERCore module in populating the reporting tables are located in ERCore
    Content. ',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access ercore content'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  // Administration views point here.
  $items['ercore/views'] = array(
    'title' => 'Administrative Views',
    'description' => 'At a glance ERCore generated reporting views related to
    NSF Reporting Tables are available here. In addition, other views such as
    flagged items for review are available in this menu flyout.',
    'page callback' => 'system_admin_menu_block_page',
    'expanded' => '1',
    'access arguments' => array('access ercore admin content'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  // Administrative actions menu.
  $items['ercore/actions'] = array(
    'title' => 'Administrative Actions',
    'description' => 'Administrative actions for administrators and staff.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access ercore admin content'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['ercore/actions/new-inst'] = array(
    'title' => 'Create New Institution',
    'description' => 'This page allows administrators to add new institutions.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_goto',
    'page arguments' => array('node/add/ercore-institution'),
    'access arguments' => array('access ercore admin content'),
  );
  $items['ercore/actions/new-user'] = array(
    'title' => 'Create New User',
    'description' => 'This page allows administrators to register new users.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/people/create'),
    'access arguments' => array('administer users'),
  );
  // ERCore module administrative pages.
  $items['ercore/actions/config'] = array(
    'title' => 'ERCore Reporting Core Settings',
    'description' => 'This area is specific to ERCore grant start dates as well as reporting period dates.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/config/ercore/admin'),
    'access arguments' => array('administer ercore module'),
  );
  // ERCore Data Integrity.
  $items['ercore/views/integrity'] = array(
    'title' => 'Data Integrity',
    'description' => 'Look for potential problems with data integrity.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ercore_data_integrity_callback'),
    'access arguments' => array('access ercore admin content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/ercore-integrity.inc',
  );
  // NSF TABLE VIEWS.
  $items['ercore/views/salary-support'] = array(
    'title' => 'NSF Table A - Salary Support',
    'description' => 'This view aims to help you determine where the Salary Support information is coming from.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nsf_table_a_callback'),
    'access arguments' => array('access ercore admin content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/ercore-table-a.inc',
  );
  $items['ercore/views/salary-support/download'] = array(
    'title' => 'Salary Support Download',
    'description' => 'Downloading Table A Excel file with arguments.',
    'page callback' => 'ercore_table_a_download_callback',
    'page arguments' => array(''),
    'access arguments' => array('access ercore excel sheets'),
    'type' => MENU_CALLBACK,
    'file' => 'pages/ercore-table-a-download.inc',
  );
  $items['ercore/views/salary-support/download/%'] = array(
    'title' => 'Salary Support Download',
    'description' => 'Downloading Table A Excel file with arguments.',
    'page callback' => 'ercore_table_a_download_callback',
    'page arguments' => array(4),
    'access arguments' => array('access ercore excel sheets'),
    'type' => MENU_CALLBACK,
    'file' => 'pages/ercore-table-a-download.inc',
  );
  $items['ercore/views/participants'] = array(
    'title' => 'NSF Table B - Participants',
    'description' => 'This view aims to help you determine where the Participant information is coming from.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nsf_table_b_callback'),
    'access arguments' => array('access ercore admin content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/ercore-table-b.inc',
  );
  $items['ercore/views/participants/download'] = array(
    'title' => 'Participants Download',
    'description' => 'Downloading Table B Excel file.',
    'page callback' => 'ercore_table_b_download_callback',
    'page arguments' => array(''),
    'access arguments' => array('access ercore excel sheets'),
    'type' => MENU_CALLBACK,
    'file' => 'pages/ercore-table-b-download.inc',
  );
  $items['ercore/views/participants/download/%'] = array(
    'title' => 'Participants Download',
    'description' => 'Downloading Table B Excel file with arguments.',
    'page callback' => 'ercore_table_b_download_callback',
    'page arguments' => array(4),
    'access arguments' => array('access ercore excel sheets'),
    'type' => MENU_CALLBACK,
    'file' => 'pages/ercore-table-b-download.inc',
  );
  $items['ercore/views/collaborations'] = array(
    'title' => 'NSF Table C - Collaborations',
    'description' => 'This view aims to help you determine where the Collaborator counts are coming from.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nsf_table_c_callback'),
    'access arguments' => array('access ercore admin content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/ercore-table-c.inc',
  );
  $items['ercore/views/collaborations/download'] = array(
    'title' => 'Collaborations Download',
    'description' => 'Downloading Table C Excel file.',
    'page callback' => 'ercore_table_c_download_callback',
    'page arguments' => array(''),
    'access arguments' => array('access ercore excel sheets'),
    'type' => MENU_CALLBACK,
    'file' => 'pages/ercore-table-c-download.inc',
  );
  $items['ercore/views/collaborations/download/%'] = array(
    'title' => 'Collaborations Download',
    'description' => 'Downloading Table C Excel file with arguments.',
    'page callback' => 'ercore_table_c_download_callback',
    'page arguments' => array(4),
    'access arguments' => array('access ercore excel sheets'),
    'type' => MENU_CALLBACK,
    'file' => 'pages/ercore-table-c-download.inc',
  );
  $items['ercore/views/external-engagement'] = array(
    'title' => 'NSF Table D - External Engagements',
    'description' => 'This view aims to help you determine where the External Engagement counts are coming from.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nsf_table_d_callback'),
    'access arguments' => array('access ercore admin content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/ercore-table-d.inc',
  );
  $items['ercore/views/external-engagement/download'] = array(
    'title' => 'External Engagements Download',
    'description' => 'Downloading Table D Excel file with arguments.',
    'page callback' => 'ercore_table_d_download_callback',
    'page arguments' => array(''),
    'access arguments' => array('access ercore excel sheets'),
    'type' => MENU_CALLBACK,
    'file' => '/pages/ercore-table-d-download.inc',
  );
  $items['ercore/views/external-engagement/download/%'] = array(
    'title' => 'External Engagements Download',
    'description' => 'Downloading Table D Excel file with arguments.',
    'page callback' => 'ercore_table_d_download_callback',
    'page arguments' => array(4),
    'access arguments' => array('access ercore excel sheets'),
    'type' => MENU_CALLBACK,
    'file' => 'pages/ercore-table-d-download.inc',
  );
  $items['ercore/views/outputs'] = array(
    'title' => 'NSF Table E - Outputs',
    'description' => 'This view aims to help you determine where the Outputs counts are coming from.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nsf_table_e_callback'),
    'access arguments' => array('access ercore admin content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/ercore-table-e.inc',
  );
  $items['ercore/views/outputs/download'] = array(
    'title' => 'Outputs Download',
    'description' => 'Downloading Table E Excel file with arguments.',
    'page callback' => 'ercore_table_e_download_callback',
    'page arguments' => array(''),
    'access arguments' => array('access ercore excel sheets'),
    'type' => MENU_CALLBACK,
    'file' => 'pages/ercore-table-e-download.inc',
  );
  $items['ercore/views/outputs/download/%'] = array(
    'title' => 'Outputs Download',
    'description' => 'Downloading Table E Excel file with arguments.',
    'page callback' => 'ercore_table_e_download_callback',
    'page arguments' => array(4),
    'access arguments' => array('access ercore excel sheets'),
    'type' => MENU_CALLBACK,
    'file' => 'pages/ercore-table-e-download.inc',
  );

  // Links to content views.
  $content_views = array(
    "calendar" => "Calendar Events",
    "collaborations" => "Collaborations",
    "collaborators" => "External Collaborators",
    "external-engagements" => "External Engagements",
    "highlights" => "Highlights",
    "awards" => "Honors and Awards",
    "institutions" => "Institutions",
    "other-research-products" => "Other Research Products",
    "participants" => "Participants",
    "patents" => "Patents",
    "presentations" => "Presentations",
    "proposals" => "Proposal or Grant",
    "publications" => "Publications",
  );
  foreach ($content_views as $url => $label) {
    $items['ercore/content/' . $url] = array(
      'title' => $label,
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'drupal_goto',
      'page arguments' => array($url),
      'access arguments' => array('access ercore content'),
    );
  }
  $items['ercore/reporting'] = array(
    'title' => 'Accomplishments',
    'description' => 'This page shows all categories of accomplishments (collaborations, grants & proposals, external engagements, etc) with the option of selecting by reporting year/period.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_goto',
    'page arguments' => array('reporting'),
    'access arguments' => array('access ercore admin content'),
  );
  $items['ercore/reporting/download'] = array(
    'title' => 'Download Reporting Tables',
    'description' => 'Downloading All NSF Tables without arguments.',
    'page callback' => 'ercore_reporting_download_callback',
    'page arguments' => array(''),
    'access arguments' => array('access ercore excel sheets'),
    'type' => MENU_CALLBACK,
    'file' => 'pages/ercore-reporting-download.inc',
  );
  $items['ercore/reporting/download/%'] = array(
    'title' => 'Download Reporting Tables',
    'description' => 'Downloading All NSF Tables with arguments.',
    'page callback' => 'ercore_reporting_download_callback',
    'page arguments' => array(3),
    'access arguments' => array('access ercore excel sheets'),
    'type' => MENU_CALLBACK,
    'file' => 'pages/ercore-reporting-download.inc',
  );
  $items['ercore/guides'] = array(
    'title' => 'User Guides',
    'description' => 'Reference guides for ERCore administrators and users.',
    'expanded' => '1',
    'weight' => '10',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access ercore content'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['ercore/admin-guide'] = array(
    'title' => 'Administrative Guide',
    'description' => 'A reference and guide for administrator and staff.',
    'weight' => '11',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'ercore_admin_guide_callback',
    'access arguments' => array('access ercore content'),
    'file' => '/pages/ercore-admin-guide.inc',
  );
  $items['ercore/guides/accounts'] = array(
    'title' => 'User: Accounts',
    'description' => 'Creating and/or editing ERCore user accounts.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'ercore_user_guide_callback',
    'access arguments' => array('access ercore content'),
    'file' => 'pages/ercore-user-guide.inc',
  );
  $items['ercore/guides/reporting-data'] = array(
    'title' => 'User: Entering Reporting Data',
    'description' => 'Creating ERCore reporting data.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'ercore_user_reporting_callback',
    'access arguments' => array('access ercore content'),
    'file' => 'pages/ercore-user-reporting.inc',
  );
  $items['ercore/guides/viewing-data'] = array(
    'title' => 'User: View Reporting Data',
    'description' => 'Viewing and editing ERCore reporting data.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'ercore_user_viewing_callback',
    'access arguments' => array('access ercore content'),
    'file' => 'pages/ercore-user-viewing.inc',
  );
  $items['ercore/guides/drupal'] = array(
    'title' => 'User: Drupal Terms and Information',
    'description' => 'Drupal information you may find helpful.',
    'weight' => '5',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'ercore_user_drupal_callback',
    'access arguments' => array('access ercore content'),
    'file' => 'pages/ercore-user-drupal.inc',
  );
  $items['ercore/guides/nsf'] = array(
    'title' => 'User: NSF Definitions',
    'description' => 'Key Term NSF Definitions and the Criteria and the System
    that Defines these Terms',
    'weight' => '5',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'ercore_user_nsf_callback',
    'access arguments' => array('access ercore content'),
    'file' => 'pages/ercore-user-nsf.inc',
  );
  $items['ercore/participants'] = array(
    'title' => 'Participant Views',
    'description' => 'Views for administrating Participants.',
    'expanded' => '1',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access ercore admin content'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  return $items;
}

/**
 * Implements hook_views_api().
 */
function ercore_admin_views_api($module, $api) {
  if ($module == 'views' && $api == 'views_default') {
    return array('version' => 2);
  }
}

/**
 * Implements hook_views_pre_execute().
 */
function ercore_admin_views_pre_execute(&$view) {
  if ($view->name == 'ercore_export_table_b_institutions') {
    // $view->args[0] = '2013-05--2014-05';.
  }
  if ($view->name == 'ercore_export_table_b_fields') {
    if ($view->args[1] != '!1') {
      $argument = $view->args[1];
      $view->footer['area']->options['content'] = "*New Hires: This column is being filtered by the date range ($argument).";
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function ercore_admin_views_query_alter(&$view, &$query) {
  if ($view->name == 'ercore_table_c_display') {
    if (isset($query->where[0])) {
      $new_query = $query->where[0];
      $where = explode(' AND ', $new_query['conditions'][0]['field']);
      $new_where = $where[1] . ' AND ' . 'field_data_field_ercore_cn_dates.field_ercore_cn_dates_value2 = field_data_field_ercore_cn_dates.field_ercore_cn_dates_value';
      $new_query['conditions'][1] = $new_query['conditions'][0];
      $new_query['conditions'][1]['field'] = $new_where;
      $new_query['type'] = 'OR';
      $query->where[0] = $new_query;
    }
  }
  if ($view->name == 'ercore_table_c_export') {
    if (isset($query->where[0]['conditions'][1])) {
      $where_field = $query->where[0]['conditions'][1]['field'];
      $where = explode(' AND ', $where_field);
      $new_where = '(' . $where_field . ') OR (' . $where[1] . ' AND ' . 'field_ercore_cn_collaborator_field_collection_item__field_data_field_ercore_cn_dates.field_ercore_cn_dates_value2 = field_ercore_cn_collaborator_field_collection_item__field_data_field_ercore_cn_dates.field_ercore_cn_dates_value' . ')';
      $query->where[0]['conditions'][1]['field'] = $new_where;
    }
  }
  if ($view->name == 'ercore_export_table_b_data_objects') {
    if (isset($query->where[0])) {
      if (isset($query->where[0]['conditions'][1])) {
        $var = '1';
      }
      else {
        $var = '0';
      }
      $where_field = $query->where[0]['conditions'][$var]['field'];
      if (strpos($where_field, 'DATE_FORMAT') !== FALSE) {
        $where = explode(' AND ', $where_field);
        $new_where = '(' . $where_field . ') OR (' . $where[1] . ' AND ' . 'field_data_field_ercore_us_part_date.field_ercore_us_part_date_value2 = field_data_field_ercore_us_part_date.field_ercore_us_part_date_value' . ')';
        $query->where[0]['conditions'][$var]['field'] = $new_where;
      }
    }
  }
  if ($view->name == 'ercore_export_table_b_totals') {
    if (isset($query->where[0])) {
      $where_field = $query->where[0]['conditions'][0]['field'];
      $where = explode(' AND ', $where_field);
      $new_where = '(' . $where_field . ') OR (' . $where[1] . ' AND ' . 'field_data_field_ercore_us_part_date.field_ercore_us_part_date_value2 = field_data_field_ercore_us_part_date.field_ercore_us_part_date_value' . ')';
      $query->where[0]['conditions'][0]['field'] = $new_where;
    }
  }
  if ($view->name == 'ercore_participant_testing' || $view->name == 'ercore_summary_participants') {
    if (isset($query->where[1])) {
      $conditions = $query->where[1]['conditions'];
      foreach ($conditions as $key => $condition) {
        $new_where = NULL;
        if (strpos($condition['field'], 'field_ercore_us_part_date_value,')) {
          $new_field1 = $condition['field'];
          $new_field1a = ' OR (' . str_replace(">=", "<=", $new_field1) . ' AND field_data_field_ercore_us_part_date.field_ercore_us_part_date_value2 = field_data_field_ercore_us_part_date.field_ercore_us_part_date_value)';
          $new_field1b = ' OR (' . str_replace(">=", "<=", $new_field1) . ' AND ' . str_replace("part_date_value,", "part_date_value2,", $new_field1) . ')';
          $new_where = $new_field1 . $new_field1a . $new_field1b;
        }
        elseif (strpos($condition['field'], 'field_ercore_us_part_date_value2,')) {
          $new_field2 = $condition['field'];
          $new_field2a = ' OR (' . str_replace("date_value2,", "date_value,", $new_field2) . ' AND field_data_field_ercore_us_part_date.field_ercore_us_part_date_value2 = field_data_field_ercore_us_part_date.field_ercore_us_part_date_value)';
          $new_field2b = ' OR (' . str_replace("date_value2,", "date_value,", $new_field2) . ' AND ' . str_replace("<=", ">=", $new_field2) . ')';
          $new_where = $new_field2 . $new_field2a . $new_field2b;
        }
        if ($new_where != NULL) {
          $query->where[1]['conditions'][$key]['field'] = $new_where;
        }
      }
    }
  }
  if ($view->name == 'ercore_summary_collaboration' || $view->name == 'ercore_summary_collaborators') {
    if (isset($query->where[1]['conditions'][1])) {
      $conditions = $query->where[1]['conditions'];
      foreach ($conditions as $key => $condition) {
        $new_where = NULL;
        if (strpos($condition['field'], 'field_ercore_cn_dates_value,')) {
          $new_field1 = $condition['field'];
          $new_field1a = ' OR (' . str_replace(">=", "<=", $new_field1) . ' AND field_data_field_ercore_cn_dates.field_ercore_cn_dates_value2 = field_data_field_ercore_cn_dates.field_ercore_cn_dates_value)';
          $new_field1b = ' OR (' . str_replace(">=", "<=", $new_field1) . ' AND ' . str_replace("ercore_cn_dates_value,", "ercore_cn_dates_value2,", $new_field1) . ')';
          $new_where = $new_field1 . $new_field1a . $new_field1b;
        }
        elseif (strpos($condition['field'], 'field_ercore_cn_dates_value2,')) {
          $new_field2 = $condition['field'];
          $new_field2a = ' OR (' . str_replace("dates_value2,", "dates_value,", $new_field2) . ' AND field_data_field_ercore_cn_dates.field_ercore_cn_dates_value2 = field_data_field_ercore_cn_dates.field_ercore_cn_dates_value)';
          $new_field2b = ' OR (' . str_replace("dates_value2,", "dates_value,", $new_field2) . ' AND ' . str_replace("<=", ">=", $new_field2) . ')';
          $new_where = $new_field2 . $new_field2a . $new_field2b;
        }
        if ($new_where != NULL) {
          $query->where[1]['conditions'][$key]['field'] = $new_where;
        }
      }
    }
  }
  if ($view->name == 'ercore_table_e_users' && $view->current_display == 'panel_pane_2') {
    if (isset($query->where[0])) {
      $field = $query->where[0]['conditions'][0]['field'];
      $where = explode(' AND ', $field);
      $field1a = ') OR (' . $where[1] . ' AND field_data_field_ercore_us_part_date.field_ercore_us_part_date_value2 = field_data_field_ercore_us_part_date.field_ercore_us_part_date_value)';
      $new_where = '(' . $field . $field1a;
      $query->where[0]['conditions'][0]['field'] = $new_where;
    }
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function ercore_admin_theme_registry_alter(&$theme_registry) {
  // Get the path to this module.
  $modulepath = drupal_get_path('module', 'ercore_admin');

  $theme_registry['views_data_export_feed_icon']['function'] = 'ercore_views_data_export_feed_icon';
  $theme_registry['views_data_export_feed_icon']['includes'][0] = $modulepath . '/includes/ercore_views_data_export.theme.inc';
}

/**
 * Implements hook_theme().
 */
function ercore_admin_theme($existing, $type, $theme, $path) {
  $theme = array(
    'ercore_summary_table' => array(
      'variables' => array(
        'ranges' => array(),
        'default_form' => TRUE,
      ),
      'function' => 'ercore_summary_table',
    ),
    'ercore_integrity' => array(
      'variables' => array(
        'ranges' => array(),
      ),
      'function' => 'ercore_integrity',

    ),
    'ercore_table_a' => array(
      'variables' => array(
        'ranges' => array(),
      ),
      'function' => 'ercore_table_a',

    ),
    'ercore_table_b' => array(
      'variables' => array(
        'ranges' => array(),
      ),
      'function' => 'ercore_table_b',

    ),
    'ercore_table_c' => array(
      'variables' => array(
        'ranges' => array(),
      ),
      'function' => 'ercore_table_c',
    ),
    'ercore_table_d' => array(
      'variables' => array(
        'ranges' => array(),
      ),
      'function' => 'ercore_table_d',
    ),
    'ercore_table_e' => array(
      'variables' => array(
        'ranges' => array(),
      ),
      'function' => 'ercore_table_e',
    ),
  );
  return $theme;
}


/**
 * Implements hook_form_alter().
 */
function ercore_admin_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form') {
    if (strpos($form['#id'], 'ercore-summary-') !== FALSE) {

      $format = variable_get('date_format_ercore_date_format_filter');
      $form['start-date']['value']['#date_format'] = $format;
      $form['end-date']['value']['#date_format'] = $format;
    }
  }
}
