<?php
/**
 * @file
 * Includes variales to be deleted on uninstall.
 */

// ERCore date formats
variable_del('date_format_ercore_date_format_day_name');
variable_del('date_format_ercore_date_format_filter');
variable_del('date_format_ercore_date_format_month_day_year');
variable_del('date_format_ercore_date_format_month_year');
variable_del('date_format_ercore_date_format_time');
variable_del('date_format_ercore_date_format_year');


// Delete ERCore set variables.
variable_del('er_start_date');
variable_del('er_reporting_month');

// Delete node-type Admin variables.
variable_del('additional_settings__active_tab_ercore_admin');
variable_del('node_preview_ercore_admin');
variable_del('node_submitted_ercore_admin');
variable_del('node_options_ercore_admin');
variable_del('menu_options_ercore_admin');
variable_del('menu_parent_ercore_admin');
variable_del('pathauto_node_ercore_admin_pattern');
variable_del('comment_ercore_admin');
variable_del('field_bundle_settings_node__ercore_admin');

// Delete node type Collaboration variables.
variable_del('additional_settings__active_tab_ercore_collaboration');
variable_del('node_preview_ercore_collaboration');
variable_del('node_submitted_ercore_collaboration');
variable_del('node_options_ercore_collaboration');
variable_del('menu_options_ercore_collaboration');
variable_del('menu_parent_ercore_collaboration');
variable_del('pathauto_node_ercore_collaboration_pattern');
variable_del('comment_ercore_collaboration');
variable_del('field_bundle_settings_node__ercore_collaboration');

// Delete collaborator field collection variables.
variable_del('field_bundle_settings_field_collection_item__field_ercore_cn_collaborator');

// Delete node-type Event variables.
variable_del('additional_settings__active_tab_ercore_event');
variable_del('node_preview_ercore_event');
variable_del('node_submitted_ercore_event');
variable_del('node_options_ercore_event');
variable_del('menu_options_ercore_event');
variable_del('menu_parent_ercore_event');
variable_del('pathauto_node_ercore_event_pattern');
variable_del('comment_ercore_event');
variable_del('field_bundle_settings_node__ercore_event');

// Delete Engagement field collection variables.
variable_del('field_bundle_settings_field_collection_item__field_ercore_ev_engagement');

// Delete node type Highlight variables.
variable_del('additional_settings__active_tab_ercore_j_highlight');
variable_del('node_preview_ercore_j_highlight');
variable_del('node_submitted_ercore_j_)highlight');
variable_del('node_options_ercore_j_highlight');
variable_del('menu_options_ercore_j_highlight');
variable_del('menu_parent_ercore_j_highlight');
variable_del('pathauto_node_ercore_j_highlight_pattern');
variable_del('comment_ercore_j_highlight');
variable_del('field_bundle_settings_node__ercore_j_highlight');

// Delete node type Honors and Awards variables.
variable_del('additional_settings__active_tab_ercore_j_honor');
variable_del('node_preview_ercore_j_honor');
variable_del('node_submitted_ercore_j_honor');
variable_del('node_options_ercore_j_honor');
variable_del('menu_options_ercore_j_honor');
variable_del('menu_parent_ercore_j_honor');
variable_del('pathauto_node_ercore_j_honor_pattern');
variable_del('comment_ercore_j_honor');
variable_del('field_bundle_settings_node__ercore_j_honor');

// Delete node type Institutions variables.
variable_del('additional_settings__active_tab_ercore_institution');
variable_del('node_preview_ercore_institution');
variable_del('node_submitted_ercore_institution');
variable_del('node_options_ercore_institution');
variable_del('menu_options_ercore_institution');
variable_del('menu_parent_ercore_institution');
variable_del('pathauto_node_ercore_institution_pattern');
variable_del('comment_ercore_institution');
variable_del('field_bundle_settings_node__ercore_institution');

// Delete node type Other Research Products variables.
variable_del('additional_settings__active_tab_ercore_other_product');
variable_del('node_preview_ercore_other_product');
variable_del('node_submitted_ercore_other_product');
variable_del('node_options_ercore_other_product');
variable_del('menu_options_ercore_other_product');
variable_del('menu_parent_ercore_other_product');
variable_del('pathauto_node_ercore_other_product_pattern');
variable_del('comment_ercore_other_product');
variable_del('field_bundle_settings_node__ercore_other_product');

// Delete node type Patent variables.
variable_del('additional_settings__active_tab_ercore_patent');
variable_del('node_preview_ercore_patent');
variable_del('node_submitted_ercore_patent');
variable_del('node_options_ercore_patent');
variable_del('menu_options_ercore_patent');
variable_del('menu_parent_ercore_patent');
variable_del('pathauto_node_ercore_patent_pattern');
variable_del('comment_ercore_patent');
variable_del('field_bundle_settings_node__ercore_patent');

// Delete node type Presentation variables.
variable_del('additional_settings__active_tab_ercore_presentation');
variable_del('node_preview_ercore_presentation');
variable_del('node_submitted_ercore_presentation');
variable_del('node_options_ercore_presentation');
variable_del('menu_options_ercore_presentation');
variable_del('menu_parent_ercore_presentation');
variable_del('pathauto_node_ercore_presentation_pattern');
variable_del('comment_ercore_presentation');
variable_del('field_bundle_settings_node__ercore_presentation');

// Delete node type Proposal variables.
variable_del('additional_settings__active_tab_ercore_proposal');
variable_del('node_preview_ercore_proposal');
variable_del('node_submitted_ercore_proposal');
variable_del('node_options_ercore_proposal');
variable_del('menu_options_ercore_proposal');
variable_del('menu_parent_ercore_proposal');
variable_del('pathauto_node_ercore_proposal_pattern');
variable_del('comment_ercore_proposal');
variable_del('field_bundle_settings_node__ercore_proposal');

// Delete node type Publication variables.
variable_del('additional_settings__active_tab_ercore_publication');
variable_del('node_preview_ercore_publication');
variable_del('node_submitted_ercore_publication');
variable_del('node_options_ercore_publication');
variable_del('menu_options_ercore_publication');
variable_del('menu_parent_ercore_publication');
variable_del('pathauto_node_ercore_publication_pattern');
variable_del('comment_ercore_publication');
variable_del('field_bundle_settings_node__ercore_publication');

// Delete vocabulary Organizational Component variables.
variable_del('components/[term:name]');
variable_del('field_bundle_settings_taxonomy_term__ercore_components');

// Delete User Variables
variable_del('field_bundle_settings_user__user');
variable_del('pathauto_user_pattern');